# Generated by Django 4.2.11 on 2025-04-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(verbose_name='Âge'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_pressure',
            field=models.FloatField(verbose_name='Pression artérielle'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diabetes_pedigree',
            field=models.FloatField(verbose_name='Hérédité'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glucose',
            field=models.FloatField(verbose_name='Taux de glucose'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insulin',
            field=models.FloatField(verbose_name='Insuline'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='outcome',
            field=models.BooleanField(blank=True, null=True, verbose_name='Diabète'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pregnancies',
            field=models.IntegerField(verbose_name='Grossesses'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='skin_thickness',
            field=models.FloatField(verbose_name='Épaisseur de peau'),
        ),
    ]
